config: {
	info: {
		"appMode": "2",
		"birthday": "1972-12-04",
		"patid": "",
		"payAccType": "0",
		"phone": "19978423625",
		"idCard": "452726197212041074",
		"address": "广西天峨县更新乡安亭村林伦屯1号",
		"name": "韦光文",
		"gender": "1",
		"type": "increase",
		"cardType": "01",
		"nation": "8"
	}
}
